### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by Hanaasagi** [SoraTenshi/german-string#1]
Hi, there seems to be a minor bug that could potentially cause a memory leak. When the string length exceeds 12, the stored `len` value is set to `len - 4`:

https://github.com/SoraTenshi/german-string/blob/862ab91e70e70fd474545b6cd41773fdb8c35c94/src/main.zig#L55

However, the condition for releasing memory relies on `len > 12`:

https://github.com/SoraTenshi/german-string/blob/862ab91e70e70fd474545b6cd41773fdb8c35c94/src/main.zig#L42

This mismatch can be reproduced with the following code:

```zig
test "test length" {
    const allocator = std.testing.allocator;

    var ger_str = try GerString.init(allocator, "0123456789123");  // 13 bytes
    defer ger_str.deinit();
}
```

**Comment by SoraTenshi** [comment]
Thank you for reporting!
Should be fixed with this commit:
https://github.com/SoraTenshi/german-string/commit/3a9dd5de540538373c70e4df8762dabc50041ced

If this issue still persists, please reopen this issue :)
